apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-openwhisk-train-cozmo
spec:
  restartPolicy: Never
  containers:
    - name: tensorflow-openwhisk-train-cozmo
      image: nheidloff/tensorflow-openwhisk-train-cozmo:latest
      imagePullPolicy: Always
      env:
      - name: AWS_ACCESS_KEY_ID
        value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: AWS_SECRET_ACCESS_KEY
        value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: COS_BUCKET_NAME
        value: tensorflow
      - name: COS_FILE_NAME
        value: cozmo-photos.zip
      - name: TF_MODEL
        value: mobilenet_0.50_224   # inception_v3, mobilenet_0.50_224, mobilenet_0.50_128, mobilenet_0.50_16
